### ISSUE TITLE
Documentation: screen shot of the GUI

### ISSUE THREAD

**Issue by hhzl** [lfkeitel/quizzer#9]
Is it possible to have a screen shot of the GUI in the README?

**Comment by lfkeitel** [comment]
I can add a screen shot. It's not the prettiest application in the world, but it's functional.

**Comment by hhzl** [comment]
Thanks! How does the [ReviewForm](https://github.com/lfkeitel/quizzer/blob/master/Quizzer/ReviewForm.cs) look like?

**Comment by lfkeitel** [comment]
I'll make screenshots of the application and put them in the screenshots folder. No need to have them all in the readme.
